### ISSUE TITLE
Session template support

### ISSUE THREAD

**Issue by falkTX** [jackaudio/new-session-manager#45]
This is something that I always find useful to have.
I would say that most people end up using the same applications in similar ways when producing music, so having a read-to-go template would be great.

Note that I am not saying that NSM should ship with pre-made templates, but that the user should be allowed to create them.
Functionality-wise we already have everything that is needed to make this work (more or less).

Would be great that when clicking "new session" we are presented with the option of "empty" and any other templates we set up before. The SM just needs to take care to duplicate the template and load it.

**Comment by diovudau** [comment]
Not only for technical reasons I see this in the responsibility of the GUI. 

Current situation is

- [good] Any existing session can be duplicated, so  sessions could be created by the user as templates
- [good] Sessions follow the directory tree, so all templates can be in a templates/ subdir
- [bad] NSM.-Duplicate works only after opening a session.
- [bad] Once again distributed network sessions may make this inconvenient, hard or impossible.

NSM design principle is to not do file manager tasks. (which is promptly violated through the Duplicate function, but let's forget that for a minute).  This is exactly the area where one must be very careful not to implement features into the daemon for a little convenience, when it cab be done easily otherwise:

Argodejo has the option to duplicate any session without opening it first (which is just copying the files while preventing name colliosions and making sure you stay in the session-root).

For Argodejo it would be relatively easy to extend that into templates by either copying sessions from and to an extra dir outside the sesion-root or treat a "template" subdir as special.
I like the latter option much more:  With other GUIs those templates will just show up as normal sessions, which they technically are, and can be opened and edited.  Even Argodejo itself can show them on demand as normal sessions again for editing purposes.

Because of this easy and frictionless implementation of the feature, for everything a user cares about, this should not be in the server.

**Comment by falkTX** [comment]
Makes sense to do it on the GUI side.

One thing that would be nice, related to this, is to tag a session to be read-only.
It is not only useful for templates, but also personally for when I do not want a session to be changed by mistake (as I found out most of NSM-GUI actions trigger a save without indicating it as such)

**Comment by diovudau** [comment]
For read-only session see here: https://github.com/linuxaudio/new-session-manager/issues/30

**Comment by diovudau** [comment]
With the changes now in git this can be considered succesfuly implemented.
