### ISSUE TITLE
Two NSM related keys for Desktop files

### ISSUE THREAD

**Issue by grammoboy2** [jackaudio/new-session-manager#96]
https://github.com/jackaudio/new-session-manager/issues/40

I understand that there are two NSM related keys for Desktop files? 
X-NSM-Capable=true
X-NSM-Exec=jackpatch

Is this really needed? To list NSM clients, wouldn't this be enough: X-NSM-Exec=jackpatch ? Keep it simple stupid?

https://github.com/jean-emmanuel/loop192/commit/4fd4f0ef83f580de9140f10f03f23885c73fc5bd
I would expect it to have this key: X-NSM-Exec=loop192, but it has only X-NSM-Capable=true. There is no X-NSM-Exec key.

A application that lists NSM clients, would only need the X-NSM-Exec key as far as I can see. 

I'm afraid with two keys, you get inconsistent implementations between different clients, as already becomes apparent with the loop192 example I think.

"It is important that this is a boolean value, so that it can be manually set to off if needed"
https://github.com/jackaudio/new-session-manager/issues/40#issuecomment-933008535

It's not possible for Carla to not add the X-NSM-Exec key to the desktop file if NSM is not supported, or set the key empty (not ideal either probably)?

Looking at these files, in it current state there is no need for an extra key as far as I can see, but ok falkTX is talking about a post-install situation, hm.
https://github.com/falkTX/Carla/tree/main/data/desktop

Edit: desktop-file-validate doesn't report an error when X-NSM-Exec has no value (X-NSM-Exec= )

FYI, reporting and closing.

**Comment by grammoboy2** [comment]
Another implementation, doesn't check for X-NSM-Exec as far as I can see:
https://github.com/Houston4444/RaySession/blob/2f4a9735a4940e65c1a2860e30dcc921d379c22c/src/daemon/list_nsm_desktop.py

These different implementations are expected I think, if you've two different keys.

**Comment by ferdnyc** [comment]
Here's my take, FWIW:

Two keys are the correct approach. At _least_ two keys. You don't want to overload the meaning of your key to answer _both_ "can I do this?" and "how do I do this?", because it boxes you in.

Look at [Agordejo's implementation](https://git.laborejo.org/lss/Agordejo/src/branch/master/engine/findprograms.py#L120-L135), for example. It looks for an `X-NSM-Exec=` key, but if it doesn't find one and the `.desktop` file advertises as `X-NSM-Capable` (or is in its whitelist), it uses the regular `Exec=` key instead.

Considering how many NSM-capable `.desktop` files contain exactly this:

```ini
Exec=fooprogram
X-NSM-Capable=true
X-NSM-Exec=fooprogram
```

That's a _good_ and _smart_ optimization — you should be able to leave out the NSM _Exec_ key if it's redundant with your normal `Exec=`, not leave out the `X-NSM-Capable=` key. That one, as was already said, is important to keep as a boolean on/off switch, and makes it possible to omit the `X-NSM-Exec=` key if it doesn't provide any unique information.

There's also the possibility that, down the line, methods of starting NSM-capable clients _other than_ exec'ing a process will come along — like D-Bus activation, for example. Then you'd have an `X-NSM-DBusServiceName=` instead of an `X-NSM-Exec=`, and `X-NSM-Capable=` would continue to have the exact same semantics it does today.
